# Generated by cucumber-sinatra. (2012-09-08 16:55:35 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Fifty

class FiftyWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  FiftyWorld.new
end
