development:
  sessions:
      default:
        database: ted_api_fifty_dev
        hosts:
          - localhost

test:
  sessions:
      default:
        database: ted_api_fifty_test
        hosts:
          - localhost

# Tell Mongoid which environment this configuration is for.
staging:
  # This starts the session configuration settings. You may have as
  # many sessions as you like, but you must have at least 1 named
  # 'default'.
  sessions:
    # Define the default session.
    default:
      # A session can have any number of hosts. Usually 1 for a single
      # server setup, and at least 3 for a replica set. Hosts must be
      # an array of host:port pairs. This session is single server.
      uri: <%= ENV['MONGOLAB_URI'] %>
  # Here we put the Mongoid specific configuration options. These are explained
  # in more detail next.
  options:
    allow_dynamic_fields: true
    identity_map_enabled: true
    # include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    skip_version_check: true
    use_activesupport_time_zone: false
    use_utc: true        
    
# Tell Mongoid which environment this configuration is for.
production:
  # This starts the session configuration settings. You may have as
  # many sessions as you like, but you must have at least 1 named
  # 'default'.
  sessions:
    # Define the default session.
    default:
      # A session can have any number of hosts. Usually 1 for a single
      # server setup, and at least 3 for a replica set. Hosts must be
      # an array of host:port pairs. This session is single server.
      uri: <%= ENV['MONGOLAB_URI'] %>
  # Here we put the Mongoid specific configuration options. These are explained
  # in more detail next.
  options:
    allow_dynamic_fields: true
    identity_map_enabled: true
    # include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    skip_version_check: true
    use_activesupport_time_zone: false
    use_utc: true